Fix possible bug wellborepath layer
equinor/esv-intersection pull request #369
Opened 2020-10-02 12:01 UTC by nicholasdalhaug

2020-10-05 08:01 UTC, Brynjulf requested changes
Your solution to part one works well.

Part two has been mischaracterised by us as a bug when it is actually a feature to clamp any values outside the curve to the curve. The real issue is to document this, which will be a separate task (#370)

So if you remove your change related to part two and clean up the imports I can approve this pull request

2020-10-09 06:58 UTC, nicholasdalhaug commented on .storybook/src/features/highlight.stories.ts
> +      max: controller.referenceSystem.length,
Are you sure it is not clamped the wrong way in that case? I see why one might want the slider to not move the point all the way to the end or start. I do not see why you would want the slider itself to not go all the way to its start or end. Anyways, I will fix it.

2020-10-09 07:10 UTC, nicholasdalhaug commented on .storybook/src/features/highlight.stories.ts
> +import { ZoomPanHandler } from '../../../src/control';
Yes, I did not realise that. Thanks!

2020-10-09 07:22 UTC, nicholasdalhaug commented
Could you do me the favor of labelling this PR with "hacktoberfest-accepted" if you think it is a valid contribution to the project?

2020-10-12 11:00 UTC, Brynjulf commented on .storybook/src/features/highlight.stories.ts
> +      max: controller.referenceSystem.length,
The slider is meant to illustrate a one-dimensional view and not the curve, in our actual use case we needed extensions to be able to handle panning past the end of the curve. We also used a mouse move event to get two-dimensional coordinates to highlight the point along the curve in other parts of our application. This also means that we needed to handle values that were outside the curve gracefully.  

That being said, there are things that can be done to improve this example but is outside the scope of this pull request at least

2020-10-12 11:00 UTC, Brynjulf approved these changes
Looks good

2020-10-12 11:01 UTC, merged

2020-10-12 11:03 UTC, Brynjulf commented
@nicholasdalhaug done. Thank you for your contribution, we appreciate it 😊