fix: print SurfaceLine label, not id
equinor/esv-intersection pull request #390
Opened 2020-11-11 07:59 UTC by ooystein

@tormy pointed out that id was used instead of label for GeomodelLabelsLayer drawLineLabel() and drawAreaLabel(). drawAreaLabel() was already fixed though in recent commit.

2020-11-11 08:52 UTC, Brynjulf requested changes
This is fixed for surface areas, but not for group areas. In the transformation for group areas you should add the `label` property (`generateGroupAreas()` in `src/datautils/surfacedata.ts`)

2020-11-11 20:46 UTC, ooystein commented
We don't use the GroupAreas stuff, so I'm not sure of the expected behavior and what should be used as label. So please have a close look at it again.

2020-11-12 08:24 UTC, HavardNJ approved these changes

2020-11-12 13:26 UTC, Brynjulf approved these changes
LGTM

2020-11-12 13:26 UTC, merged