WIP POC Shared PIXI Context
equinor/esv-intersection pull request #491
Opened 2022-09-21 13:29 UTC by schoening

2022-09-23 12:06 UTC, ooystein requested changes
I suggest we create a new long loved branch for this new effort since we don't know how we want this to end up.

Recreate this PR against a branch on master and we can work as normal with PRs against that branch. When branch starts to settle we can merge it in to master and keep all the commit history on that branch.

I know we usually avoid long lived branches, but I don't see any issues with doing it here, now for the undertaking we working on.

2022-09-23 12:06 UTC, ooystein commented on src/layers/base/PixiLayer.ts
> +      const container = document.createElement('div');
why not directly assign to this._pixiViewContainer ?

2022-09-26 08:32 UTC, schoening commented on src/layers/base/PixiLayer.ts
> -    }
The pixi cleanup has do be done by the code that passes in the Pixi Application. The PixiLayer.ts no longer creates it's own Pixi Application.

2022-09-26 08:33 UTC, ooystein commented on src/layers/base/PixiLayer.ts
> -    }
But I didn't seems to find this cleanup kept anywhere

2022-09-26 08:40 UTC, ooystein commented on src/layers/base/PixiLayer.ts
_container still has it's underscore

2022-09-26 08:41 UTC, ooystein commented on src/layers/base/PixiLayer.ts
> -    }
I still don't see this anywhere in the code

2022-09-26 08:59 UTC, schoening commented on src/layers/base/PixiLayer.ts
Because we are exposing a getter with the name container.

2022-09-26 10:12 UTC, ovineq commented on src/layers/base/PixiLayer.ts
> -    }
Moved it into the `PixiRenderApplication` on destruction 👍🏻

2022-09-27 10:47 UTC, ooystein approved these changes
:100:

2022-09-27 11:02 UTC, merged