feat: Add new completion layer for tubing & screen
equinor/esv-intersection pull request #500
Opened 2022-10-03 07:34 UTC by ovineq

Ported from wellx-designer

2022-10-03 07:44 UTC, ovineq commented
Corresponding data needs to be merged first: https://github.com/equinor/esv-intersection-data/pull/9

2022-10-03 10:17 UTC, ooystein requested changes
Looking good, a couple small adjustments and it should be ready.

2022-10-03 10:17 UTC, ooystein commented on .storybook/src/data.ts
> +  completionV2,
Let delete existing completion data in esv-intersection-data repo and place our new data there. So we call it "completion" not "completionV2"

2022-10-03 10:17 UTC, ooystein commented on src/layers/CompletionLayerV2.ts
> +export class CompletionLayerV2<T extends Completion[]> extends WellboreBaseComponentLayer<T> {
Use CompletionLayer as name. Old layer was never implemented and was just acting as a placeholder.

2022-10-04 06:55 UTC, ooystein approved these changes

2022-10-04 09:10 UTC, merged