fix: Remove referenceId from Perforations
equinor/esv-intersection pull request #518
Opened 2022-11-10 14:34 UTC by ovineq

We need a second look on the rendering here after the `referenceId` is removed @schoening

2022-12-13 14:23 UTC, ovineq reviewed
Some things to clean up. Might need to pair-review the rest.

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +  ctx.fillStyle = perforationOptions.yellow;
Can be cleaned up

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +const createTexture = (canvas: HTMLCanvasElement) => {
Seems to be related to perforations, let's change the naming to be more related.

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +const createCanvas = (perfShape: ComplexRopeSegment, options: PerforationOptions): { canvas: HTMLCanvasElement; ctx: CanvasRenderingContext2D } => {
Seems to be related to perforations, let's change the naming to be more related.

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> -  const { /*fracLineLength,*/ packingOpacity } = perforationOptions;
Remove comment

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +    // );
Remove commented code

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +  _otherPerforations: Perforation[],
Unused

2022-12-13 14:23 UTC, ovineq commented on src/datautils/schematicShapeGenerator.ts
> +  _otherPerforations: Perforation[],
Unused

2022-12-13 14:23 UTC, ovineq commented on src/layers/SchematicLayer.ts
> +        // const otherPerforations = perforations.filter((p) => p.id !== perforation.id);
Unused

2022-12-13 14:23 UTC, ovineq commented on src/layers/SchematicLayer.ts
> +        // const otherPerforations = perforations.filter((p) => p.id !== perforation.id);
Unused

2022-12-13 14:23 UTC, ovineq commented on src/layers/SchematicLayer.ts
> +    // PERFORATION RENDER LOGIC
Remove comment

2022-12-15 10:08 UTC, ooystein commented
Please update PR name and add description with anything the reviewer needs to know @schoening @ovineq

2022-12-15 13:36 UTC, ooystein requested changes
Exited to see this! Just a few simple comments and this should be ready!

2022-12-21 13:42 UTC, ooystein approved these changes
:shipit:

2022-12-21 13:47 UTC, merged