feat/vite storybook 7
equinor/esv-intersection pull request #529
Opened 2022-12-28 15:39 UTC by ooystein

2022-12-28 16:10 UTC, ooystein commented
I have tested to link pacakge localy to compare the new build and it seems to work fine. But I encourage reviewers to test this PR against existing projects dependent on this library.

2022-12-29 08:41 UTC, ovineq requested changes
Great work 🥳 
I'm liking the new categorization of the stories in v7. And Vite makes it is so ~blazingly~ fast!
Just a few comments:

2022-12-29 08:41 UTC, ovineq commented on vite.config.ts
> +      fileName: 'index',
![image](https://user-images.githubusercontent.com/91891939/209924276-6432cba0-1eb0-49d9-8c1f-8e34a71fb5f7.png)
The default file endings got my eyebrow moving. Could we instead use the conventional file endings for the different formats?
```suggestion
      fileName: (format) => {
        const fileName = 'index'
        switch(format) {
          case 'es':
            return `${fileName}.mjs`
          case 'cjs':
            return `${fileName}.cjs`
          case 'umd':
            return `${fileName}.umd.js`
          default:
            return `${fileName}.js`
        }
      },
```
```package.json
  "exports": {
    "import": "./dist/index.mjs",
    "require": "./dist/index.cjs",
    "browser": "./dist/index.umd.js"
  },
```

2022-12-29 08:43 UTC, ovineq commented
> I have tested to link pacakge localy to compare the new build and it seems to work fine. But I encourage reviewers to test this PR against existing projects dependent on this library.

Also tested linking these changes for our usage. Seems to work just fine 🎉

2022-12-29 09:08 UTC, ooystein commented on .github/workflows/github-pages.yml
> +      run: npm run storybook build -c .storybook -o docs_out/storybook/${{ github.ref.name }}
very good catch!

2022-12-29 09:20 UTC, ooystein commented
Fixed review comments

2022-12-29 09:21 UTC, ovineq approved these changes
:shipit:

2022-12-29 09:33 UTC, merged